#!/bin/bash

if test -p /dev/stdin; 
then
   mapfile -t data < /dev/stdin
else
   data=( "$@" )
fi

counter=${#data[@]};

if [ $counter -lt 1  ]; then
      echo "$0 : error : no arguments given"
      exit 1001
fi

if [ $counter -gt 1  ]; then
      echo "$0 : error : too many arguments given"
      exit 1002
fi

. "/usr/local/bin/fcgi_util/fcgi_config/trap"

ln -sf $spawn_dir/${data[0]} $pepper_dir/app.sock
