#!/bin/bash

. "/usr/local/bin/fcgi_util/fcgi_config/perm"

flag=false
while getopts ":l" opt; do
  case $opt in
    l)
      flag=true
      find "$spawn_dir" -iname '*.sock'
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

[[ "$flag" = false  ]] && ls -1 "$spawn_dir" | grep '.sock'
