#!/bin/bash


if [ ! -w "/usr/local/bin"  ];then
   echo "write on /usr/local/bin : permission denied"
   exit 1
fi


path_full="$(readlink -f $0)"
path_dire="$(dirname $path_full)"


pushd /usr/local/bin
find "$path_dire" -name "fcgi*" -type f -exec ln -fs {} . ';' 
popd
