#!/bin/bash


if [ ! -w "/usr/local/bin"  ];then
   echo "write on /usr/local/bin : permission denied"
   exit 1
fi


path_full="$(readlink -f $0)"
path_dire="$(dirname $path_full)"


pushd /usr/local/bin
find . -name "fcgi*" -type l -exec rm {} ';' 
popd

rm -rf "$path_dire"
